### ISSUE TITLE
[task] improve readme/documentations with separate install and section documentation

### ISSUE THREAD

**Issue by mckaygerhard** [h5gs/wallacepos#3]
improve the current documentations to make more sense to usage and deploy, we need to catch more users, this is a macro task for others ones

## Context

current README are overhead and pretty unorganized.. also we need user base documentation

## Expected result

more firently user README and separate technical files for installation

## Current result

largte README with only apache crap instructions.. i used lighttpd

## Task TODO

- [ ] selft assigned to me! @h5gs 
- [ ] new readme more slim with splited install file isntructions
- [ ] provide wiki links or md files with minimal documetnations (i prefers the second)
- [ ] made a `docs` directory inside the project with minimal files (in future we can separate in an other repo)
- [ ] complete and checked the files that any link are not missing when previous taks are done!

i was the creator of the main structure of the opensourcepos wiki https://github.com/osposweb/ospos-wiki/graphs/contributors (i forked if those guys block the real results, wiki was a crapo before me) the main structure and ideas to the actual information.. 

## extra info (if wiki is deleted cos those guys are pretty stupid)

![imagen](https://user-images.githubusercontent.com/1571724/134527460-27067f55-da6b-4502-a356-4f18ec57b0bf.png)
